### ISSUE TITLE
Update terraform to 1.0.0

### ISSUE THREAD

**Issue by sanyer** [ContainerSolutions/terraform-examples#46]

**Comment by teszes** [comment]
Can you elaborate on what this would entail?

**Comment by ttarczynski** [comment]
I would assume that to make this update we need to:

1. Set the required terraform version to ">= 1.0.0" in all examples
```
terraform {
  required_version = ">= 1.0.0"
}
```
2. Change CI definitions to use Terraform >= 1.0.0
  - https://github.com/ContainerSolutions/terraform-examples/blob/main/.github/workflows/main.yml 
  - here for tflint:
```
        - name: Terraform Validate
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: v0.28.0 # Must be specified. See: https://github.com/terraform-linters/tflint/releases for latest versions
```
  - don't know how to bump terraform version for `Providers*` CI jobs, e.g.:
```
  ProvidersAWS:
    concurrency: provider_test_aws
    needs: [TFLint, TFValidate, Checks]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0   # Need whole history, or at least far enough back to get .test_log.log reference
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Run AWS examples
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CI_USE_TF_CLOUD: true
          TERRAFORM_CLOUD_LOGIN_TOKEN: ${{ secrets.TERRAFORM_CLOUD_LOGIN_TOKEN }}
        if: github.ref == 'refs/heads/main' || env.GITHUB_REF_SLUG == 'integration' # Only run on main/integration, as these take a long time
        run: ${{ github.workspace }}/bin/run_aws_examples.sh
```
 
----

Docs:

- 1) 
  - https://www.terraform.io/docs/language/settings/index.html#specifying-a-required-terraform-version
  - https://www.terraform.io/docs/language/expressions/version-constraints.html
  
- 2) Not sure yet how to do this
  - https://github.com/terraform-linters/setup-tflint
  - https://github.com/terraform-linters/tflint/releases
